name: CI/CD Node JS

on:
    push:
        branches:
            - main

# env:
#   MY_VARIABLE: 'This is a variable'

jobs:
    unit_test_jest:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./src

        strategy:
            matrix:
                node-version: [20.x]
        
        steps:
        - name: Checkout - Récuparation du projet
          uses: actions/checkout@v4
        - name: Liste des fichiers et répertoires du dossier courant
          run: ls
        - name: Installation des dépendances
          run: npm install
        - name: Liste des dépendances installées
          run: npm list
        - name: Test avec Jest
          run: ./node_modules/.bin/jest test/sum.test.js
          uses: codecov/codecov-action@v4
          with:
            fail_ci_if_error: true # optional (default = false)
            files: ./coverage1.xml,./coverage2.xml # optional
            flags: unittests # optional
            name: codecov-umbrella # optional
            token: ${{ secrets.CODECOV_TOKEN }} # required
            verbose: true # optional (default = false)


    check_success:
      runs-on: ubuntu-latest
      if: always() && (needs.unit_test_jest.result == 'success')
      needs: [unit_test_jest]
      steps:
      - name: Annonce que le job est en cours           
        run: |
          echo "Second Job Running"
