name: CI/CD Node JS

on:
    push:
        branches:
            - main

# env:
#   MY_VARIABLE: 'This is a variable'

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]
        
        steps:
        - name: Checkout - Récuparation du projet
          uses: actions/checkout@v4
          with:
          - name: Setup Node
            working-directory: ./src
        - name: Liste des fichiers et répertoires du dossier courant
          run: ls
        # - name: Changement du dossier & Liste des fichiers et répertoires du dossier courant
        #   run: cd source & ls
        # - name: Installation des dépendances
        #   run: npm install
        # - name: Liste des fichiers et répertoires du dossier courant
        #   run: ls
        