name: CI/CD Node JS

on:
    push:
        branches:
            - main

# env:
#   MY_VARIABLE: 'This is a variable'

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x]
        
        steps:
        - name: Checkout - Récuparation du projet
          uses: actions/checkout@v4
        - name: Changement du dossier
          run: cd source
          with:
            node-version: '20.x'
        - name: Installation des dépendances
          run: npm install
        - name: Liste des fichiers et répertoires du dossier courant
          run: ls
        