name: CI/CD Node JS

on:
    push:
        branches:
            - main

# env:
#   MY_VARIABLE: 'This is a variable'

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./src

        strategy:
            matrix:
                node-version: [20.x]
        
        steps:
        - name: Checkout - Récuparation du projet
          uses: actions/checkout@v4
        - name: Liste des fichiers et répertoires du dossier courant
          run: ls
        - name: Installation des dépendances
          run: npm install
        - name: Test avec Jest
          run: jest test/sum.test.js

        